# Generated by Django 2.2 on 2019-04-13 19:52

from django.db import migrations


def insert_halls(apps, schema_editor):
    Hall = apps.get_model('cinema', 'Hall')
    Hall.objects.create(
        name='White dwarf',
        rows_number=7,
        seats_per_row=15,
        cleaning_duration=10,
    )
    Hall.objects.create(
        name='Black hole',
        rows_number=10,
        seats_per_row=20,
    )
    Hall.objects.create(
        name='Great attractor',
        rows_number=10,
        seats_per_row=20,
    )
    Hall.objects.create(
        name='Universe',
        rows_number=20,
        seats_per_row=40,
        cleaning_duration=20,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_halls)
    ]
